package server

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	difflogic "github.com/jacktea/data-smith/internal/datasmith/diff"
	local "github.com/jacktea/data-smith/internal/datasmith/migrate/local"
	"github.com/jacktea/data-smith/pkg/conn"
	"github.com/jacktea/data-smith/pkg/consts"
	pkgmigrate "github.com/jacktea/data-smith/pkg/migrate"
)

// scriptNameRe mirrors the migration filename grammar in
// internal/datasmith/migrate/local; direction is captured raw so files without
// an explicit .up/.down report "".
var scriptNameRe = regexp.MustCompile(`^([vV]\d+(?:\.\d+)*|\d+)__([^.]+)(?:\.(up|down))?\.(sql|json)$`)

var versionOnlyRe = regexp.MustCompile(`^[vV]?(\d+(?:\.\d+)*)$`)

type scriptInfo struct {
	FileName   string    `json:"fileName"`
	Version    string    `json:"version"`
	Title      string    `json:"title"`
	Direction  string    `json:"direction"`
	Ext        string    `json:"ext"`
	Size       int64     `json:"size"`
	ModifiedAt time.Time `json:"modifiedAt"`
}

func (s scriptInfo) isUp() bool { return s.Direction == "" || s.Direction == "up" }

// --- library CRUD -----------------------------------------------------------

type libraryRequest struct {
	Name string `json:"name"`
}

func (s *Server) handleListLibraries(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, s.store.ListLibraries())
}

func (s *Server) handleCreateLibrary(w http.ResponseWriter, r *http.Request) {
	var req libraryRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	if strings.TrimSpace(req.Name) == "" {
		writeError(w, http.StatusBadRequest, "脚本库名称不能为空")
		return
	}
	lib := &LibraryMeta{
		ID:        newID("lib"),
		Name:      req.Name,
		CreatedAt: time.Now(),
		Versions:  map[string]VersionMeta{},
	}
	if err := os.MkdirAll(s.libraryDirUnchecked(lib.ID), 0o755); err != nil {
		writeError(w, http.StatusInternalServerError, "创建脚本库目录失败: %v", err)
		return
	}
	if err := s.store.PutLibrary(lib); err != nil {
		respondStoreErr(w, err)
		return
	}
	writeJSON(w, http.StatusOK, lib)
}

func (s *Server) handleDeleteLibrary(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	unlock := s.lockLibrary(id)
	defer unlock()
	found, err := s.store.DeleteLibrary(id)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	if !found {
		writeError(w, http.StatusNotFound, "脚本库不存在")
		return
	}
	// 连带删除脚本目录。
	_ = os.RemoveAll(s.libraryDirUnchecked(id))
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

// libraryDirUnchecked joins the library scripts directory without existence
// checks (callers validate beforehand).
func (s *Server) libraryDirUnchecked(libID string) string {
	return filepath.Join(s.dataDir, "libraries", libID)
}

// libraryDir resolves and validates the scripts directory of an existing
// library.
func (s *Server) libraryDir(libID string) (string, error) {
	if _, ok := s.store.GetLibrary(libID); !ok {
		return "", errBad("脚本库不存在")
	}
	return s.libraryDirUnchecked(libID), nil
}

// --- scripts ----------------------------------------------------------------

func (s *Server) handleListScripts(w http.ResponseWriter, r *http.Request) {
	libID := r.PathValue("id")
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	scripts, err := listScripts(dir)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "读取脚本目录失败: %v", err)
		return
	}
	writeJSON(w, http.StatusOK, scripts)
}

func listScripts(dir string) ([]scriptInfo, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return []scriptInfo{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := []scriptInfo{}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		matches := scriptNameRe.FindStringSubmatch(entry.Name())
		if matches == nil {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		out = append(out, scriptInfo{
			FileName:   entry.Name(),
			Version:    matches[1],
			Title:      matches[2],
			Direction:  matches[3],
			Ext:        matches[4],
			Size:       info.Size(),
			ModifiedAt: info.ModTime(),
		})
	}
	sort.Slice(out, func(i, k int) bool {
		if cmp := local.CompareVersion(out[i].Version, out[k].Version); cmp != 0 {
			return cmp < 0
		}
		if out[i].Direction != out[k].Direction {
			return out[i].Direction == "" || out[i].Direction == "up" && out[k].Direction == "down"
		}
		return out[i].FileName < out[k].FileName
	})
	return out, nil
}

// parseScriptName validates a client-provided script file name and returns its
// parsed fields. When allowDown is false, down scripts are rejected: they are
// only generated by version registration (read/delete/download still accept
// them so registered versions remain manageable).
func parseScriptName(fileName string, allowDown bool) (*scriptInfo, error) {
	if fileName == "" || fileName != filepath.Base(fileName) || strings.ContainsAny(fileName, `/\`) {
		return nil, errBad("非法的脚本文件名: %s", fileName)
	}
	matches := scriptNameRe.FindStringSubmatch(fileName)
	if matches == nil {
		return nil, errBad("脚本文件名须形如 V1__描述.sql 或 1.2.0__描述.up.sql")
	}
	if matches[3] == "down" && !allowDown {
		return nil, errBad("down 脚本仅能通过版本登记生成")
	}
	if matches[4] == "json" {
		return nil, errBad("仅支持 .sql 脚本(JSON 迁移不受支持)")
	}
	return &scriptInfo{
		FileName:  fileName,
		Version:   matches[1],
		Title:     matches[2],
		Direction: matches[3],
		Ext:       matches[4],
	}, nil
}

type scriptContentRequest struct {
	FileName string `json:"fileName"`
	Content  string `json:"content"`
}

func (s *Server) handleCreateScript(w http.ResponseWriter, r *http.Request) {
	libID := r.PathValue("id")
	unlock := s.lockLibrary(libID)
	defer unlock()
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	var req scriptContentRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	info, err := parseScriptName(req.FileName, false)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	path := filepath.Join(dir, info.FileName)
	if _, err := os.Stat(path); err == nil {
		writeError(w, http.StatusBadRequest, "脚本 %s 已存在,请使用编辑", info.FileName)
		return
	}
	if err := os.WriteFile(path, []byte(req.Content), 0o644); err != nil {
		writeError(w, http.StatusInternalServerError, "写入脚本失败: %v", err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"fileName": info.FileName, "content": req.Content})
}

func (s *Server) handleGetScript(w http.ResponseWriter, r *http.Request) {
	dir, err := s.libraryDir(r.PathValue("id"))
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	fileName := r.PathValue("fileName")
	if _, err := parseScriptName(fileName, true); err != nil {
		respondStoreErr(w, err)
		return
	}
	raw, err := os.ReadFile(filepath.Join(dir, fileName))
	if err != nil {
		writeError(w, http.StatusNotFound, "脚本不存在")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"fileName": fileName, "content": string(raw)})
}

func (s *Server) handlePutScript(w http.ResponseWriter, r *http.Request) {
	libID := r.PathValue("id")
	unlock := s.lockLibrary(libID)
	defer unlock()
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	fileName := r.PathValue("fileName")
	if _, err := parseScriptName(fileName, false); err != nil {
		respondStoreErr(w, err)
		return
	}
	var req scriptContentRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	path := filepath.Join(dir, fileName)
	if _, err := os.Stat(path); err != nil {
		writeError(w, http.StatusNotFound, "脚本不存在")
		return
	}
	if err := os.WriteFile(path, []byte(req.Content), 0o644); err != nil {
		writeError(w, http.StatusInternalServerError, "写入脚本失败: %v", err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"fileName": fileName, "content": req.Content})
}

func (s *Server) handleDeleteScript(w http.ResponseWriter, r *http.Request) {
	libID := r.PathValue("id")
	if s.beforeLibraryMutation != nil {
		s.beforeLibraryMutation(libID, "delete-script")
	}
	unlock := s.lockLibrary(libID)
	defer unlock()
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	fileName := r.PathValue("fileName")
	info, err := parseScriptName(fileName, true)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	path := filepath.Join(dir, fileName)
	if _, err := os.Stat(path); err != nil {
		writeError(w, http.StatusNotFound, "脚本不存在")
		return
	}
	if err := os.Remove(path); err != nil {
		writeError(w, http.StatusInternalServerError, "删除脚本失败: %v", err)
		return
	}
	// C8：up 是迁移版本的可执行入口；删掉后即使 down 仍保留，版本登记
	// 也必须同步清理，否则 store.json 会暴露一个无法执行的版本。
	if err := s.removeVersionMetaIfNoUp(dir, libID, info.Version); err != nil {
		writeError(w, http.StatusInternalServerError, "脚本已删除,但清理版本元数据失败: %v", err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

// removeVersionMetaIfNoUp 在删除脚本后检查该版本是否仍有 up 可执行入口；
// 没有则删除登记元数据。扫描或持久化失败会返回给调用方，不能伪装成成功。
func (s *Server) removeVersionMetaIfNoUp(dir, libID, version string) error {
	scripts, err := s.listLibraryScripts(dir)
	if err != nil {
		return fmt.Errorf("扫描脚本目录: %w", err)
	}
	normalized := normalizedVersion(version)
	for _, script := range scripts {
		if normalizedVersion(script.Version) == normalized && script.isUp() {
			return nil
		}
	}
	if err := s.deleteVersionMeta(libID, normalized); err != nil {
		return fmt.Errorf("删除版本 %s 元数据: %w", normalized, err)
	}
	return nil
}

// SweepOrphanVersionMeta 是 store 一致性自检：清理「已无 up 可执行入口」的
// 孤儿版本登记，返回各脚本库被清理的版本（键为脚本库 ID）。扫描或持久化
// 失败时同时返回此前已完成的清理和错误，调用方不能把部分成功当普通成功。
func (s *Server) SweepOrphanVersionMeta() (map[string][]string, error) {
	removed := map[string][]string{}
	for _, lib := range s.store.ListLibraries() {
		unlock := s.lockLibrary(lib.ID)
		scripts, err := s.listLibraryScripts(s.libraryDirUnchecked(lib.ID))
		if err != nil {
			unlock()
			return removed, fmt.Errorf("扫描脚本库 %s: %w", lib.ID, err)
		}
		present := make(map[string]bool, len(scripts))
		for _, script := range scripts {
			if script.isUp() {
				present[normalizedVersion(script.Version)] = true
			}
		}
		for version := range lib.Versions {
			if present[version] {
				continue
			}
			if err := s.deleteVersionMeta(lib.ID, version); err != nil {
				unlock()
				return removed, fmt.Errorf("删除脚本库 %s 版本 %s 元数据: %w", lib.ID, version, err)
			}
			removed[lib.ID] = append(removed[lib.ID], version)
		}
		unlock()
	}
	for libID := range removed {
		sort.Strings(removed[libID])
	}
	return removed, nil
}

func (s *Server) handleDownloadScript(w http.ResponseWriter, r *http.Request) {
	dir, err := s.libraryDir(r.PathValue("id"))
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	fileName := r.PathValue("fileName")
	path, err := safeArtifactPath(dir, fileName)
	if err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	serveFileAttachment(w, r, path, fileName)
}

// --- version registration ---------------------------------------------------

type registerVersionRequest struct {
	SourceJobID          string `json:"sourceJobId"`
	CompanionJobID       string `json:"companionJobId"`
	IncludeSchema        bool   `json:"includeSchema"`
	IncludeData          bool   `json:"includeData"`
	Version              string `json:"version"`
	Title                string `json:"title"`
	ExpectedConnectionID string `json:"expectedConnectionId"`
}

func (s *Server) handleRegisterVersion(w http.ResponseWriter, r *http.Request) {
	libID := r.PathValue("id")
	if s.beforeLibraryMutation != nil {
		s.beforeLibraryMutation(libID, "register-version")
	}
	unlock := s.lockLibrary(libID)
	defer unlock()
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	var req registerVersionRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	if !req.IncludeSchema && !req.IncludeData {
		writeError(w, http.StatusBadRequest, "includeSchema 与 includeData 至少选择一项")
		return
	}
	version, err := normalizeRegistrationVersion(req.Version)
	if err != nil {
		writeError(w, http.StatusBadRequest, "%s", err.Error())
		return
	}
	if req.Title == "" || strings.ContainsAny(req.Title, ".") {
		writeError(w, http.StatusBadRequest, "版本标题不能为空且不能包含点号")
		return
	}
	job := s.jobs.Get(req.SourceJobID)
	if job == nil {
		writeError(w, http.StatusBadRequest, "来源任务不存在")
		return
	}
	if job.Type() != JobDiffSchema && job.Type() != JobDiffData && job.Type() != JobDiffFull {
		writeError(w, http.StatusBadRequest, "来源任务类型必须为 diff-schema、diff-data 或 diff-full")
		return
	}
	if job.Status() != jobStatusSucceeded {
		writeError(w, http.StatusBadRequest, "来源任务尚未成功完成")
		return
	}
	// 完全对比任务在单一目录内同时产出结构与数据产物,不允许再挂配套任务。
	var companion *Job
	if req.CompanionJobID != "" {
		if job.Type() == JobDiffFull {
			writeError(w, http.StatusBadRequest, "完全对比任务已包含结构与数据产物,无需配套任务")
			return
		}
		companion = s.jobs.Get(req.CompanionJobID)
		if companion == nil {
			writeError(w, http.StatusBadRequest, "配套任务不存在")
			return
		}
		if companion.ID() == job.ID() {
			writeError(w, http.StatusBadRequest, "配套任务不能与来源任务相同")
			return
		}
		if companion.Status() != jobStatusSucceeded {
			writeError(w, http.StatusBadRequest, "配套任务尚未成功完成")
			return
		}
		if companion.Type() == job.Type() {
			writeError(w, http.StatusBadRequest, "配套任务类型必须与来源任务互补(diff-schema / diff-data)")
			return
		}
	}
	var schemaJob, dataJob *Job
	switch job.Type() {
	case JobDiffSchema:
		schemaJob = job
	case JobDiffData:
		dataJob = job
	default: // JobDiffFull: 结构与数据产物在同一任务目录
		schemaJob = job
		dataJob = job
	}
	if companion != nil {
		if companion.Type() == JobDiffSchema {
			schemaJob = companion
		} else {
			dataJob = companion
		}
	}
	if req.IncludeSchema && schemaJob == nil {
		writeError(w, http.StatusBadRequest, "勾选了结构变更但没有可用的结构比对任务")
		return
	}
	if req.IncludeData && dataJob == nil {
		writeError(w, http.StatusBadRequest, "勾选了数据变更但没有可用的数据比对任务")
		return
	}
	if err := s.checkVersionUnique(dir, version); err != nil {
		respondStoreErr(w, err)
		return
	}

	var schemaForward, schemaRollback, dataForward, dataRollback string
	readFrom := func(from *Job, name string) (string, error) {
		raw, err := os.ReadFile(filepath.Join(from.Dir(), name))
		if err != nil {
			if os.IsNotExist(err) {
				return "", errBad("任务 %s 缺少产物 %s,无法登记", from.ID(), name)
			}
			return "", fmt.Errorf("读取任务产物 %s: %w", name, err)
		}
		return string(raw), nil
	}
	if req.IncludeSchema {
		var err error
		if schemaForward, err = readFrom(schemaJob, difflogic.SchemaDiffForwardFile); err != nil {
			writeError(w, http.StatusBadRequest, "%s", err.Error())
			return
		}
		schemaRollback, _ = readFrom(schemaJob, difflogic.SchemaDiffRollbackFile)
	}
	if req.IncludeData {
		var err error
		if dataForward, err = readFrom(dataJob, difflogic.DataDiffForwardFile); err != nil {
			writeError(w, http.StatusBadRequest, "%s", err.Error())
			return
		}
		dataRollback, _ = readFrom(dataJob, difflogic.DataDiffRollbackFile)
	}

	upContent, downContent := difflogic.AssembleVersionScripts(
		req.IncludeSchema, req.IncludeData,
		schemaForward, schemaRollback, dataForward, dataRollback,
	)

	upFile := fmt.Sprintf("V%s__%s.up.sql", version, req.Title)
	downFile := fmt.Sprintf("V%s__%s.down.sql", version, req.Title)
	if err := os.WriteFile(filepath.Join(dir, upFile), []byte(upContent), 0o644); err != nil {
		writeError(w, http.StatusInternalServerError, "写入 up 脚本失败: %v", err)
		return
	}
	if err := os.WriteFile(filepath.Join(dir, downFile), []byte(downContent), 0o644); err != nil {
		writeError(w, http.StatusInternalServerError, "写入 down 脚本失败: %v", err)
		return
	}
	if err := s.store.SetVersionMeta(libID, version, VersionMeta{ExpectedConnectionID: req.ExpectedConnectionID}); err != nil {
		respondStoreErr(w, err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"upFile": upFile, "downFile": downFile})
}

// checkVersionUnique rejects a registration version that already exists among
// the library's up scripts (normalized comparison).
func (s *Server) checkVersionUnique(dir, version string) error {
	scripts, err := listScripts(dir)
	if err != nil {
		return err
	}
	for _, script := range scripts {
		if script.Direction == "down" {
			continue
		}
		if normalizedVersion(script.Version) == version {
			return errBad("版本 %s 已存在于脚本库(%s)", version, script.FileName)
		}
	}
	return nil
}

func normalizeRegistrationVersion(version string) (string, error) {
	matches := versionOnlyRe.FindStringSubmatch(strings.TrimSpace(version))
	if matches == nil {
		return "", errBad("版本号须为点分数字(如 1.0.0)")
	}
	return matches[1], nil
}

func normalizedVersion(version string) string {
	return strings.TrimPrefix(strings.ToLower(strings.TrimSpace(version)), "v")
}

// --- migrate plan -----------------------------------------------------------

type ledgerRow struct {
	Version       string `json:"version"`
	Title         string `json:"title"`
	Status        string `json:"status"`
	Checksum      string `json:"checksum"`
	AppliedAt     string `json:"appliedAt"`
	ExecutionTime int64  `json:"executionTime"`
	ErrorSummary  string `json:"errorSummary"`
}

type latestAppliedView struct {
	Version   string `json:"version"`
	AppliedAt string `json:"appliedAt"`
}

type pendingMigrationView struct {
	Version string `json:"version"`
	Title   string `json:"title"`
}

type migratePlanView struct {
	LatestApplied *latestAppliedView     `json:"latestApplied"`
	Applied       []ledgerRow            `json:"applied"`
	Pending       []pendingMigrationView `json:"pending"`
	NextVersion   string                 `json:"nextVersion"`
	// Warnings 列出扫描脚本库时被跳过的不合规文件名（不参与迁移链），
	// 前端在推进迁移前展示，避免「迁移缺版本」被静默吞掉。
	Warnings []string `json:"warnings,omitempty"`
}

func (s *Server) handleMigratePlan(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	libID := q.Get("libraryId")
	connectionID := q.Get("connectionId")
	targetVersion := q.Get("targetVersion")
	dir, err := s.libraryDir(libID)
	if err != nil {
		respondStoreErr(w, err)
		return
	}
	stored, ok := s.store.GetConnection(connectionID)
	if !ok {
		writeError(w, http.StatusBadRequest, "连接不存在")
		return
	}
	adapter, err := s.openAdapter(r.Context(), stored.ConnConfig())
	if err != nil {
		writeError(w, http.StatusBadRequest, "连接数据库失败: %v", err)
		return
	}
	defer adapter.Close()

	rows, err := readLedger(r.Context(), adapter)
	if err != nil {
		// 老版本建的账本可能缺 checksum 等列:先用引擎的 EnsureVersionTable
		// 幂等自愈表结构,再重试一次读取;正常路径保持只读。
		if healErr := pkgmigrate.EnsureVersionTable(adapter); healErr != nil {
			writeError(w, http.StatusBadRequest, "修复迁移账本失败: %v", healErr)
			return
		}
		rows, err = readLedger(r.Context(), adapter)
	}
	if err != nil {
		writeError(w, http.StatusBadRequest, "读取迁移账本失败: %v", err)
		return
	}
	if rows == nil {
		rows = []ledgerRow{}
	}
	successSet := make(map[string]bool, len(rows))
	latest := (*latestAppliedView)(nil)
	for i := len(rows) - 1; i >= 0; i-- {
		if rows[i].Status == "success" {
			successSet[normalizedVersion(rows[i].Version)] = true
			if latest == nil {
				latest = &latestAppliedView{Version: rows[i].Version, AppliedAt: rows[i].AppliedAt}
			}
		}
	}

	files, skipped, err := local.ScanMigrations(dir)
	if err != nil {
		writeError(w, http.StatusBadRequest, "扫描脚本库失败: %v", err)
		return
	}
	local.SortMigrations(files)
	var warnings []string
	for _, name := range skipped {
		warnings = append(warnings, fmt.Sprintf("跳过不合规迁移文件名(不参与迁移链): %s", name))
	}
	pending := []pendingMigrationView{}
	for _, f := range files {
		if f.Direction != "up" {
			continue
		}
		if targetVersion != "" && local.CompareVersion(f.Version, targetVersion) > 0 {
			continue
		}
		if successSet[normalizedVersion(f.Version)] {
			continue
		}
		pending = append(pending, pendingMigrationView{
			Version: normalizedVersion(f.Version),
			Title:   f.Title,
		})
	}
	writeJSON(w, http.StatusOK, migratePlanView{
		LatestApplied: latest,
		Applied:       rows,
		Pending:       pending,
		NextVersion:   nextLibraryVersion(dir),
		Warnings:      warnings,
	})
}

// readLedger returns all schema_migrations rows ordered by id, or nil when the
// ledger table does not exist yet.
func readLedger(ctx context.Context, adapter conn.DBAdapter) ([]ledgerRow, error) {
	dbType := adapter.GetConfig().Type
	var existsQuery string
	switch dbType {
	case consts.DBTypeMySQL:
		existsQuery = "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = database() AND table_name = 'schema_migrations'"
	case consts.DBTypePostgres:
		existsQuery = "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'schema_migrations'"
	default:
		return nil, fmt.Errorf("不支持的数据库类型: %s", dbType)
	}
	var count int
	if err := adapter.GetConn().QueryRowContext(ctx, existsQuery).Scan(&count); err != nil {
		return nil, err
	}
	if count == 0 {
		return nil, nil
	}
	dbRows, err := adapter.GetConn().QueryContext(ctx,
		"SELECT version, title, checksum, status, applied_at, execution_time, error_summary FROM schema_migrations ORDER BY id")
	if err != nil {
		return nil, err
	}
	defer dbRows.Close()
	out := []ledgerRow{}
	for dbRows.Next() {
		var row ledgerRow
		var title, checksum, errorSummary, appliedAt sqlNullString
		var executionTime sqlNullInt64
		if err := dbRows.Scan(&row.Version, &title, &checksum, &row.Status, &appliedAt, &executionTime, &errorSummary); err != nil {
			return nil, err
		}
		row.Title = title.value()
		row.Checksum = checksum.value()
		row.AppliedAt = appliedAt.value()
		row.ExecutionTime = executionTime.value()
		row.ErrorSummary = errorSummary.value()
		out = append(out, row)
	}
	return out, dbRows.Err()
}

// sqlNullString/sqlNullInt64 are tiny scan targets keeping the ledger read
// tolerant of NULL columns.
type sqlNullString struct {
	set bool
	v   string
}

func (n *sqlNullString) Scan(src any) error {
	n.set = src != nil
	if s, ok := src.(string); ok {
		n.v = s
	} else if b, ok := src.([]byte); ok {
		n.v = string(b)
	} else if t, ok := src.(time.Time); ok {
		n.v = t.Format(time.RFC3339)
	} else if src != nil {
		return errors.New("ledger: 非字符串列")
	}
	return nil
}

func (n *sqlNullString) value() string { return n.v }

type sqlNullInt64 struct {
	set bool
	v   int64
}

func (n *sqlNullInt64) Scan(src any) error {
	n.set = src != nil
	switch value := src.(type) {
	case int64:
		n.v = value
	case []byte:
		parsed, err := strconv.ParseInt(string(value), 10, 64)
		if err != nil {
			return err
		}
		n.v = parsed
	case nil:
	default:
		return errors.New("ledger: 非整数列")
	}
	return nil
}

func (n *sqlNullInt64) value() int64 { return n.v }

// nextLibraryVersion bumps the last numeric segment of the library's maximum
// version; an empty library starts at 1.0.0.
func nextLibraryVersion(dir string) string {
	scripts, err := listScripts(dir)
	if err != nil || len(scripts) == 0 {
		return "1.0.0"
	}
	maxVersion := ""
	for _, script := range scripts {
		normalized := normalizedVersion(script.Version)
		if maxVersion == "" || local.CompareVersion(normalized, maxVersion) > 0 {
			maxVersion = normalized
		}
	}
	if maxVersion == "" {
		return "1.0.0"
	}
	parts := strings.Split(maxVersion, ".")
	last := parts[len(parts)-1]
	number, err := strconv.Atoi(last)
	if err != nil {
		return maxVersion + ".1"
	}
	parts[len(parts)-1] = strconv.Itoa(number + 1)
	return strings.Join(parts, ".")
}
