# sourceDb:
#   type: postgres
#   host: 192.168.11.220
#   port: 5432
#   user: example_user
#   password: obvious-placeholder
#   dbname: airedge2.1db
#   tableSchema: public

# targetDb:
#   type: postgres
#   host: 192.168.11.220
#   port: 5433
#   user: example_user
#   password: obvious-placeholder
#   dbname: airedge2.1db
#   tableSchema: public
# targetDb:
#   type: postgres
#   host: localhost
#   port: 5432
#   user: example_user
#   password: obvious-placeholder
#   dbname: airedge2.1db
#   tableSchema: public

sourceDb:
  type: postgres
  host: localhost
  port: 5432
  user: example_user
  password: obvious-placeholder
  dbname: airedge3.6db
  tableSchema: public

targetDb:
  type: postgres
  host: localhost
  port: 5432
  user: example_user
  password: obvious-placeholder
  dbname: airedge3.7db
  tableSchema: public
