sourceDb:
  type: postgres
  host: 192.168.11.220
  port: 5432
  user: airedge
  password: air20220401
  dbname: airedge2.1db
  tableSchema: public

targetDb:
  type: postgres
  host: 192.168.11.220
  port: 5433
  user: airedge
  password: air20220401
  dbname: airedge2.1db
  tableSchema: public
# targetDb:
#   type: postgres
#   host: localhost
#   port: 5432
#   user: postgres
#   password: air20220401
#   dbname: airedge2.1db
#   tableSchema: public
